// Content below is autogenerated by ojster template engine
// usually there is no reason to edit it manually
"use strict";
var inherits = require('util').inherits;
var LayoutTemplate = require('../layout');

var Page = function (opt_data, opt_ctx, opt_writer) {
  LayoutTemplate.call(this, opt_data, opt_ctx, opt_writer);
};
inherits(Page, LayoutTemplate);


Page.prototype.renderBlockContentInternal = function () { // @7:1
  var self = this;
  var d = this.data, vars = this.vars;
  self.writer.write(
    '<h2>Типовые ошибки</h2><h3 id="error401">Требуется авторизация</h3><p>HTTP статус — 401. Ответ:</p><pre js>{\n  error: {\n    code: <a href=\'',
    this.routePath('datatypes'), // @14:20
    '#ErrorCode_WRONG_TOKEN\'>ErrorCode.WRONG_TOKEN</a>',
    '\n  ', // @14:101
    '}\n}</pre><h3 id="error404">Объект не найден</h3><p>HTTP статус — 404. Ответ:</p><pre js>{\n  error: {\n    code: <a href=\'',
    this.routePath('datatypes'), // @23:20
    '#ErrorCode_NOT_FOUND\'>ErrorCode.NOT_FOUND</a>',
    '\n  ', // @23:97
    '}\n}</pre><h3 id="error500">Ошибка сервера</h3><p>HTTP статус — 500. Ответ:</p><pre js>{\n  error: {\n    code: <a href=\'',
    this.routePath('datatypes'), // @32:20
    '#ErrorCode_SERVER_ERROR\'>ErrorCode.SERVER_ERROR</a>',
    '\n  ', // @32:103
    '}\n}</pre><h3 id="errorAccessDenied">Отказано в доступе</h3><p>HTTP статус — 403. Ответ:</p><pre js>{\n  error: {\n    code: <a href=\'',
    this.routePath('datatypes'), // @41:20
    '#ErrorCode_ACCESS_DENIED\'>ACCESS_DENIED.WRONG_PARAMS</a>',
    '\n  ', // @41:108
    '}\n}</pre><h3 id="errorWrongParams">Некорректные входные данные</h3><p>Выдается в случае, если одно или несколько полей запроса неверные.</p><p>HTTP статус — 403. Ответ:</p><pre js>{\n  error: {\n    code: <a href=\'',
    this.routePath('datatypes'), // @51:20
    '#ErrorCode_WRONG_PARAMS\'>ErrorCode.WRONG_PARAMS</a>,\n    params: Array.&lt;{code: <a href=\'',
    this.routePath('datatypes'), // @52:39
    '#ErrorCode\'>ErrorCode</a>, name: string}&gt;\n  }\n}</pre><p>Пример ответа для запроса <a href="',
    this.routePath('me'), // @56:39
    '#addEducation">добавления образования текущему пользователю</a>, если не указано поле <code>school</code>:</p><pre js>{\n  error: {\n    code: 3,\n    params: [{\n      code: 6,\n      name: \'school\'\n    }]\n  }\n}</pre>'
  );
}; // @68:1

module.exports = Page;
