// Content below is autogenerated by ojster template engine
// usually there is no reason to edit it manually
"use strict";
var inherits = require('util').inherits;
var LayoutTemplate = require('../layout');

var Page = function (opt_data, opt_ctx, opt_writer) {
  LayoutTemplate.call(this, opt_data, opt_ctx, opt_writer);
};
inherits(Page, LayoutTemplate);


Page.prototype.renderBlockContentInternal = function () { // @7:1
  var self = this;
  var d = this.data, vars = this.vars;
  self.writer.write(
    '<p>Для соединения с чат-сервером используется библиотека <a href="http://socket.io/">socket.io</a>. <a href="',
    this.routePath('datatypes'), // @9:109
    '#Settings_webSocketUrls">Адреса подключения</a> можно получить при <a href="',
    this.routePath('settings'), // @9:217
    '#get">запросе настроек приложения</a>.\n  При открытии соединения в HTTP запрос добавляется GET параметр <code>token</code>, полученный при <a href="',
    this.routePath('auth'), // @10:110
    '#signin">авторизации пользователя</a>.</p>'
  );
}; // @12:1

module.exports = Page;
