// Content below is autogenerated by ojster template engine
// usually there is no reason to edit it manually
"use strict";
var inherits = require('util').inherits;
var LayoutTemplate = require('../../layout');

var Page = function (opt_data, opt_ctx, opt_writer) {
  LayoutTemplate.call(this, opt_data, opt_ctx, opt_writer);
};
inherits(Page, LayoutTemplate);


Page.prototype.renderBlockContentInternal = function () { // @7:1
  var self = this;
  var d = this.data, vars = this.vars;
  self.writer.write(
    '<p>Все данные отправляются в первом аргументе как JSON-объект.</p><h2>Закончилась активность пользователя</h2><div class=\'request\'><div class=\'path\'>activityEnd</div></div><p>Команда должна отправляться через 90 секунд после неактивности пользователя.</p><h2>Пользователь стал активен</h2><div class=\'request\'><div class=\'path\'>activityStart</div></div><h2>Отправить сообщение</h2><div class=\'request\'><div class=\'path\'>sendMessage</div></div><table class=\'params\'><caption>Данные</caption><thead><tr><th>Название</th><th>Тип</th><th>Описание</th></tr></thead><tbody><tr><td><code>id</code></td><td><code>uint</code></td><td>Идентификатор, который отправится обратно клиенту с подтверждением отправки сообщения</td></tr><tr><td><code>destinationId</code></td><td><code>uint</code></td><td>Идентификатор <a href="',
    this.routePath('datatypes'), // @43:34
    '#User">получателя</a></td></tr><tr><td><code>text</code></td><td><code>string</code></td><td>Текст сообщения</td></tr></tbody></table><h2>Прочтение сообщений текущим пользователем</h2><div class=\'request\'><div class=\'path\'>messagesRead</div></div><table class=\'params\'><caption>Данные</caption><thead><tr><th>Название</th><th>Тип</th><th>Описание</th></tr></thead><tbody><tr><td><code>sourceId</code></td><td><code>uint</code></td><td>Идентификатор <a href="',
    this.routePath('datatypes'), // @70:34
    '#User">пользователя</a>, чьи сообщения прочитаны</td></tr><tr><td><code>date</code></td><td><code><a href="',
    this.routePath('datatypes'), // @74:26
    '#DateTime">DateTime</a></code></td><td>Дата и время, до которых прочитаны сообщения</td></tr></tbody></table><p>При прочтении сообщений пользователем клиент должен оповестить об этом сервер, иначе эти сообщения будут повторно выданы как непрочитанные.</p><h2>Текущий пользователь закончил печатать сообщение</h2><div class=\'request\'><div class=\'path\'>typingFinish</div></div><table class=\'params\'><caption>Данные</caption><thead><tr><th>Название</th><th>Тип</th><th>Описание</th></tr></thead><tbody><tr><td><code>destinationId</code></td><td><code>uint</code></td><td>Идентификатор <a href="',
    this.routePath('datatypes'), // @98:34
    '#User">пользователя</a>, которому печаталось сообщение</td></tr></tbody></table><h2>Текущий пользователь начал печатать сообщение</h2><div class=\'request\'><div class=\'path\'>typingStart</div></div><table class=\'params\'><caption>Данные</caption><thead><tr><th>Название</th><th>Тип</th><th>Описание</th></tr></thead><tbody><tr><td><code>destinationId</code></td><td><code>uint</code></td><td>Идентификатор <a href="',
    this.routePath('datatypes'), // @120:34
    '#User">пользователя</a>, которому печатается сообщение</td></tr></tbody></table><h2>Прочтение уведомления</h2><div class=\'request\'><div class=\'path\'>notificationRead</div></div><table class=\'params\'><caption>Данные</caption><thead><tr><th>Название</th><th>Тип</th><th>Описание</th></tr></thead><tbody><tr><td><code>id</code></td><td><code>uint</code></td><td>Идентификатор <a href="',
    this.routePath('datatypes'), // @142:34
    '#Notification">уведомления</a></td></tr></tbody></table><h2>Прочтение всех уведомлений</h2><div class=\'request\'><div class=\'path\'>allNotificationsRead</div></div>'
  );
}; // @151:1

module.exports = Page;
