// Content below is autogenerated by ojster template engine
// usually there is no reason to edit it manually
"use strict";
var inherits = require('util').inherits;
var LayoutTemplate = require('../../layout');

var Page = function (opt_data, opt_ctx, opt_writer) {
  LayoutTemplate.call(this, opt_data, opt_ctx, opt_writer);
};
inherits(Page, LayoutTemplate);


Page.prototype.renderBlockContentInternal = function () { // @7:1
  var self = this;
  var d = this.data, vars = this.vars;
  self.writer.write(
    '<p>Все данные отправляются в первом аргументе как JSON-объект.</p><h2 id="error">Ошибка</h2><div class=\'request\'><div class=\'path\'>error</div></div><table class=\'params\'><caption>Данные</caption><thead><tr><th>Название</th><th>Тип</th><th>Описание</th></tr></thead><tbody><tr><td><code>error</code></td><td><code><a href="',
    this.routePath('datatypes'), // @26:26
    '#Error">Error</a></code></td><td>Объект ошибки</td></tr></tbody></table><h2>Перезагрузка</h2><div class=\'request\'><div class=\'path\'>reload</div></div><p>Информирует о том, что нужно снова <a href="',
    this.routePath('settings'), // @36:48
    '#get">запросить настройки приложения</a> и <a href="',
    this.routePath('auth'), // @36:131
    '#signin">произвести авторизацию</a>.</p><h2>Обновились данные текущего пользователя</h2><div class=\'request\'><div class=\'path\'>meUpdate</div></div><table class=\'params\'><caption>Данные</caption><thead><tr><th>Название</th><th>Тип</th><th>Описание</th></tr></thead><tbody><tr><td><code>user</code></td><td><code><a href="',
    this.routePath('datatypes'), // @54:26
    '#MyUser">MyUser</a></code></td><td>Данные текущего пользователя</td></tr></tbody></table><h2>Новое сообщение от пользователя</h2><div class=\'request\'><div class=\'path\'>message</div></div><table class=\'params\'><caption>Данные</caption><thead><tr><th>Название</th><th>Тип</th><th>Описание</th></tr></thead><tbody><tr><td><code>message</code></td><td><code><a href="',
    this.routePath('datatypes'), // @76:26
    '#Message">Message</a></code></td><td>Сообщение</td></tr></tbody></table><h2>Сообщения прочитаны</h2><div class=\'request\'><div class=\'path\'>messagesRead</div></div><table class=\'params\'><caption>Данные</caption><thead><tr><th>Название</th><th>Тип</th><th>Описание</th></tr></thead><tbody><tr><td><code>destinationId</code></td><td><code>uint</code></td><td>Идентификатор <a href="',
    this.routePath('datatypes'), // @99:34
    '#User">получателя</a></td></tr><tr><td><code>date</code></td><td><code><a href="',
    this.routePath('datatypes'), // @103:26
    '#DateTime">DateTime</a></code></td><td>Дата и время, до которых прочитаны сообщения</td></tr></tbody></table><h2>Сообщение отправлено</h2><div class=\'request\'><div class=\'path\'>messageSent</div></div><table class=\'params\'><caption>Данные</caption><thead><tr><th>Название</th><th>Тип</th><th>Описание</th></tr></thead><tbody><tr><td><code>destinationId</code></td><td><code>uint</code></td><td>Идентификатор <a href="',
    this.routePath('datatypes'), // @126:34
    '#User">получателя</a></td></tr><tr><td><code>message</code></td><td><code><a href="',
    this.routePath('datatypes'), // @130:26
    '#Message">Message</a></code></td><td>Сообщение</td></tr></tbody></table><h2>Пользователь ушел в оффлайн</h2><div class=\'request\'><div class=\'path\'>userOffline</div></div><table class=\'params\'><caption>Данные</caption><thead><tr><th>Название</th><th>Тип</th><th>Описание</th></tr></thead><tbody><tr><td><code>userId</code></td><td><code>uint</code></td><td>Идентификатор <a href="',
    this.routePath('datatypes'), // @153:34
    '#User">пользователя</a></td></tr></tbody></table><h2>Пользователь появился в онлайне</h2><div class=\'request\'><div class=\'path\'>userOnline</div></div><table class=\'params\'><caption>Данные</caption><thead><tr><th>Название</th><th>Тип</th><th>Описание</th></tr></thead><tbody><tr><td><code>userId</code></td><td><code>uint</code></td><td>Идентификатор <a href="',
    this.routePath('datatypes'), // @175:34
    '#User">пользователя</a></td></tr></tbody></table><h2>Пользователь закончил писать сообщение</h2><div class=\'request\'><div class=\'path\'>typingFinish</div></div><table class=\'params\'><caption>Данные</caption><thead><tr><th>Название</th><th>Тип</th><th>Описание</th></tr></thead><tbody><tr><td><code>userId</code></td><td><code>uint</code></td><td>Идентификатор <a href="',
    this.routePath('datatypes'), // @197:34
    '#User">пользователя</a></td></tr></tbody></table><h2>Пользователь начал писать сообщение</h2><div class=\'request\'><div class=\'path\'>typingStart</div></div><table class=\'params\'><caption>Данные</caption><thead><tr><th>Название</th><th>Тип</th><th>Описание</th></tr></thead><tbody><tr><td><code>userId</code></td><td><code>uint</code></td><td>Идентификатор <a href="',
    this.routePath('datatypes'), // @219:34
    '#User">пользователя</a></td></tr></tbody></table><h2>Новое уведомление</h2><div class=\'request\'><div class=\'path\'>notification</div></div><table class=\'params\'><caption>Данные</caption><thead><tr><th>Название</th><th>Тип</th><th>Описание</th></tr></thead><tbody><tr><td><code>notification</code></td><td><code><a href="',
    this.routePath('datatypes'), // @240:26
    '#Notification">Notification</a></code></td><td>Уведомление</td></tr></tbody></table><h2>Обновление настроек текущего пользователя</h2><div class=\'request\'><div class=\'path\'>mySettingsUpdate</div></div><table class=\'params\'><caption>Данные</caption><thead><tr><th>Название</th><th>Тип</th><th>Описание</th></tr></thead><tbody><tr><td><code>settings</code></td><td><code><a href="',
    this.routePath('datatypes'), // @262:26
    '#MySettings">MySettings</a></code></td><td>Новые настройки пользователя</td></tr></tbody></table>'
  );
}; // @267:1

module.exports = Page;
