// Content below is autogenerated by ojster template engine
// usually there is no reason to edit it manually
"use strict";
var inherits = require('util').inherits;
var LayoutTemplate = require('../../layout');

var Page = function (opt_data, opt_ctx, opt_writer) {
  LayoutTemplate.call(this, opt_data, opt_ctx, opt_writer);
};
inherits(Page, LayoutTemplate);


Page.prototype.renderBlockContentInternal = function () { // @7:1
  var self = this;
  var d = this.data, vars = this.vars;
  self.writer.write(
    '<h2>Список контактов</h2><div class=\'request\'><div class=\'method\'>GET</div><div class=\'path\'>/v201405/contacts</div><div class=\'auth\'>Требуется <a href="',
    this.routePath('auth'), // @12:40
    '#signin">авторизация</a></div></div><p>Ответ:</p><pre js>{\n  data: {\n    users: Array.&lt;<a href="',
    this.routePath('datatypes'), // @18:31
    '#User">User</a>&gt;,\n    messages: Object.&lt;<a href="',
    this.routePath('datatypes'), // @19:35
    '#Message">Message</a>&gt;\n  }\n}</pre><p>Список контактов выдается по свежести последнего сообщения.</p><p>Ключи объекта <code>messages</code> содержат идентификаторы пользователей, значения — последние сообщения.</p><h2>Удаление контакта</h2><div class=\'request\'><div class=\'method\'>POST</div><div class=\'path\'>/v201405/contacts/&lt;id&gt;/remove</div><div class=\'auth\'>Требуется <a href="',
    this.routePath('auth'), // @30:40
    '#signin">авторизация</a></div></div><table class=\'params\'><caption>Параметры адресной строки</caption><thead><tr><th>Название</th><th>Тип</th><th>Описание</th></tr></thead><tbody><tr><td><code>id</code></td><td><code>uint</code></td><td>Идентификатор <a href="',
    this.routePath('datatypes'), // @45:34
    '#User">контакта</a></td></tr></tbody></table><p>Ответ:</p><pre js>{\n  data: {\n    id: uint // Идентификатор удаленного контакта\n  }\n}</pre>'
  );
}; // @57:1

module.exports = Page;
