// Content below is autogenerated by ojster template engine
// usually there is no reason to edit it manually
"use strict";
var inherits = require('util').inherits;
var LayoutTemplate = require('../../layout');

var Page = function (opt_data, opt_ctx, opt_writer) {
  LayoutTemplate.call(this, opt_data, opt_ctx, opt_writer);
};
inherits(Page, LayoutTemplate);


Page.prototype.renderBlockContentInternal = function () { // @7:1
  var self = this;
  var d = this.data, vars = this.vars;
  self.writer.write(
    '<h2 id=\'get\'>Список географических локаций</h2><div class=\'request\'><div class=\'method\'>GET</div><div class=\'path\'>/v201405/geo</div></div><table class=\'params\'><caption>GET параметры</caption><thead><tr><th>Название</th><th>Тип</th><th>Описание</th></tr></thead><tbody><tr><td><code>city_ids</code></td><td><code>string=</code></td><td>Идентификаторы <a href="',
    this.routePath('datatypes'), // @26:35
    '#City">городов</a>, разделенных запятыми</td></tr><tr><td><code>country_ids</code></td><td><code>string=</code></td><td>Идентификаторы <a href="',
    this.routePath('datatypes'), // @31:35
    '#Country">стран</a>, разделенных запятыми</td></tr><tr><td><code>region_ids</code></td><td><code>string=</code></td><td>Идентификаторы <a href="',
    this.routePath('datatypes'), // @36:35
    '#Region">регионов</a>, разделенных запятыми</td></tr></tbody></table><p>Ответ:</p><pre js>{\n  cities: Array.&lt;<a href="',
    this.routePath('datatypes'), // @43:30
    '#City">City</a>&gt;,\n  countries: Array.&lt;<a href="',
    this.routePath('datatypes'), // @44:33
    '#Country">Country</a>&gt;,\n  regions: Array.&lt;<a href="',
    this.routePath('datatypes'), // @45:31
    '#Region">Region</a>&gt;\n}</pre><h2>Поиск географических локаций</h2><div class=\'request\'><div class=\'method\'>GET</div><div class=\'path\'>/v201405/geo/find</div></div><table class=\'params\'><caption>GET параметры</caption><thead><tr><th>Название</th><th>Тип</th><th>Описание</th></tr></thead><tbody><tr><td><code>query</code></td><td><code>string</code></td><td>Строка запроса</td></tr><tr><td><code>limit</code></td><td><code>uint=</code></td><td>Ограничение в количестве городов. Максимум — 20</td></tr></tbody></table><p>Осуществляет поиск городов по строке. Поиск осуществляется без учета регистра.</p><p>Ответ:</p><pre js>{\n  cities: Array.&lt;<a href="',
    this.routePath('datatypes'), // @80:30
    '#City">City</a>&gt;,\n  countries: Array.&lt;<a href="',
    this.routePath('datatypes'), // @81:33
    '#Country">Country</a>&gt;,\n  regions: Array.&lt;<a href="',
    this.routePath('datatypes'), // @82:31
    '#Region">Region</a>&gt;\n}</pre><p>Порядок, в котором отдаются города:</p><ol><li>Строка запроса и название города совпадают.</li><li>Полное название города начинается со строки запроса.</li><li>Строка запроса присутствует в полном названиии города.</li></ol>'
  );
}; // @91:1

module.exports = Page;
