// Content below is autogenerated by ojster template engine
// usually there is no reason to edit it manually
"use strict";
var inherits = require('util').inherits;
var LayoutTemplate = require('../../layout');

var Page = function (opt_data, opt_ctx, opt_writer) {
  LayoutTemplate.call(this, opt_data, opt_ctx, opt_writer);
};
inherits(Page, LayoutTemplate);


Page.prototype.renderBlockContentInternal = function () { // @7:1
  var self = this;
  var d = this.data, vars = this.vars;
  self.writer.write(
    '<h2>Получение данных о пользователе</h2><div class=\'request\'><div class=\'method\'>GET</div><div class=\'path\'>/v201405/me</div><div class=\'auth\'>Требуется <a href="',
    this.routePath('auth'), // @12:40
    '#signin">авторизация</a></div></div><p>Ответ:</p><pre js>{\n  data: {\n    user: <a href="',
    this.routePath('datatypes'), // @18:20
    '#MyUser">MyUser</a>',
    '\n  ', // @18:71
    '}\n}</pre><h2>Обновление настроек фильтра текущего пользователя</h2><div class=\'request\'><div class=\'method\'>PUT</div><div class=\'path\'>/v201405/me/filter</div><div class=\'auth\'>Требуется <a href="',
    this.routePath('auth'), // @27:40
    '#signin">авторизация</a></div></div><table class=\'params\'><caption>PUT параметры</caption><thead><tr><th>Название</th><th>Тип</th><th>Описание</th></tr></thead><tbody><tr><td><code>cityIds</code></td><td><code>string=</code></td><td>Идентификаторы <a href="',
    this.routePath('datatypes'), // @42:35
    '#City">городов</a>, разделенных запятыми</td></tr><tr><td><code>genders</code></td><td><code>string=</code></td><td>Идентификаторы <a href="',
    this.routePath('datatypes'), // @47:35
    '#Gender">полов</a>, разделенных запятыми</td></tr><tr><td><code>maxAge</code></td><td><code>uint=</code></td><td>Максимальный возраст</td></tr><tr><td><code>minAge</code></td><td><code>uint=</code></td><td>Минимальный возраст</td></tr><tr><td><code>viewType</code></td><td><code><a href="',
    this.routePath('datatypes'), // @61:26
    '#FilterViewType">FilterViewType</a>=</code></td><td>Режим просмотра пользователей</td></tr></tbody></table><p>Ответ:</p><pre js>{\n  data: true\n}</pre><h2>Добавление достижения в карьере</h2><div class=\'request\'><div class=\'method\'>POST</div><div class=\'path\'>/v201405/me/career</div></div><table class=\'params\'><caption>POST параметры</caption><thead><tr><th>Название</th><th>Тип</th><th>Описание</th></tr></thead><tbody><tr><td><code>companyId</code></td><td><code>uint=</code></td><td>Идентификатор <a href="',
    this.routePath('datatypes'), // @91:34
    '#Company">компании</a></td></tr><tr><td><code>companyName</code></td><td><code>string=</code></td><td>Название <a href="',
    this.routePath('datatypes'), // @96:29
    '#Company">компании</a></td></tr><tr><td><code>fromYear</code></td><td><code>uint=</code></td><td>Год начала</td></tr><tr><td><code>postId</code></td><td><code>uint=</code></td><td>Идентификатор <a href="',
    this.routePath('datatypes'), // @106:34
    '#CareerPost">должности</a></td></tr><tr><td><code>postName</code></td><td><code>string=</code></td><td>Название <a href="',
    this.routePath('datatypes'), // @111:29
    '#CareerPost">должности</a></td></tr><tr><td><code>toYear</code></td><td><code>uint=</code></td><td>Год окончания</td></tr></tbody></table><p>Одно из двух полей — <code>companyId</code> и <code>companyName</code> — обязательно.</p><p>Ответ:</p><pre js>{\n  data: <a href="',
    this.routePath('datatypes'), // @124:18
    '#CareerItem">CareerItem</a>',
    '\n', // @124:77
    '}</pre><p>В случае пустого значения параметров <code>companyId</code> и <code>companyName</code> или если компания с данным идентификатором не была найдена в базе, выдается ответ со статусом 403 и данными:</p><pre js>{\n  error: {\n    code: <a href=\'',
    this.routePath('datatypes'), // @131:20
    '#ErrorCode_WRONG_PARAMS\'>ErrorCode.WRONG_PARAMS</a>,\n    params: [{\n      code: <a href=\'',
    this.routePath('datatypes'), // @133:22
    '#ErrorCode_REQUIRED\'>ErrorCode.REQUIRED</a>,\n      name: \'company\'\n    }]\n  }\n}</pre><h2>Удаление достижения в карьере</h2><div class=\'request\'><div class=\'method\'>DELETE</div><div class=\'path\'>/v201405/me/career</div></div><table class=\'params\'><caption>GET параметры</caption><thead><tr><th>Название</th><th>Тип</th><th>Описание</th></tr></thead><tbody><tr><td><code>ids</code></td><td><code>string</code></td><td>Идентификаторы <a href="',
    this.routePath('datatypes'), // @158:35
    '#CareerItem">достижений в карьере</a>, разделенных запятыми</td></tr></tbody></table><p>В ответ выдается список идентификаторов <a href="',
    this.routePath('datatypes'), // @162:53
    '#CareerItem">достижений в карьере</a>, которые были удалены у пользователя:</p><pre js>{\n  data: Array.&lt;uint&gt;\n}</pre><h2>Добавление языка</h2><div class=\'request\'><div class=\'method\'>POST</div><div class=\'path\'>/v201405/me/languages</div></div><table class=\'params\'><caption>POST параметры</caption><thead><tr><th>Название</th><th>Тип</th><th>Описание</th></tr></thead><tbody><tr><td><code>name</code></td><td><code>string</code></td><td>Название языка</td></tr></tbody></table><p>Ответ:</p><pre js>{\n  data: <a href="',
    this.routePath('datatypes'), // @194:18
    '#Language">Language</a>',
    '\n', // @194:73
    '}</pre><p>В случае пустого значения параметра <code>name</code> выдается ответ со статусом 403 и данными:</p><pre js>{\n  error: {\n    code: <a href=\'',
    this.routePath('datatypes'), // @201:20
    '#ErrorCode_WRONG_PARAMS\'>ErrorCode.WRONG_PARAMS</a>,\n    params: [{\n      code: <a href=\'',
    this.routePath('datatypes'), // @203:22
    '#ErrorCode_REQUIRED\'>ErrorCode.REQUIRED</a>,\n      name: \'name\'\n    }]\n  }\n}</pre><h2>Удаление языков</h2><div class=\'request\'><div class=\'method\'>DELETE</div><div class=\'path\'>/v201405/me/languages</div></div><table class=\'params\'><caption>GET параметры</caption><thead><tr><th>Название</th><th>Тип</th><th>Описание</th></tr></thead><tbody><tr><td><code>ids</code></td><td><code>string</code></td><td>Идентификаторы <a href="',
    this.routePath('datatypes'), // @228:35
    '#Language">языков</a>, разделенных запятыми</td></tr></tbody></table><p>В ответ выдается список идентификаторов <a href="',
    this.routePath('datatypes'), // @232:53
    '#Language">языков</a>, которые были удалены у пользователя:</p><pre js>{\n  data: Array.&lt;uint&gt;\n}</pre><h2>Добавление места</h2><div class=\'request\'><div class=\'method\'>POST</div><div class=\'path\'>/v201405/me/places</div></div><table class=\'params\'><caption>POST параметры</caption><thead><tr><th>Название</th><th>Тип</th><th>Описание</th></tr></thead><tbody><tr><td><code>cityId</code></td><td><code>uint</code></td><td>Идентификатор <a href="',
    this.routePath('datatypes'), // @257:34
    '#City">города</a></td></tr><tr><td><code>name</code></td><td><code>string</code></td><td>Название места</td></tr></tbody></table><p>Ответ:</p><pre js>{\n  data: <a href="',
    this.routePath('datatypes'), // @269:18
    '#Place">Place</a>',
    '\n', // @269:67
    '}</pre><p>В случае пустого значения параметра <code>name</code> выдается ответ со статусом 403 и данными:</p><pre js>{\n  error: {\n    code: <a href=\'',
    this.routePath('datatypes'), // @276:20
    '#ErrorCode_WRONG_PARAMS\'>ErrorCode.WRONG_PARAMS</a>,\n    params: [{\n      code: <a href=\'',
    this.routePath('datatypes'), // @278:22
    '#ErrorCode_REQUIRED\'>ErrorCode.REQUIRED</a>,\n      name: \'name\'\n    }]\n  }\n}</pre><h2>Удаление мест</h2><div class=\'request\'><div class=\'method\'>DELETE</div><div class=\'path\'>/v201405/me/places</div></div><table class=\'params\'><caption>GET параметры</caption><thead><tr><th>Название</th><th>Тип</th><th>Описание</th></tr></thead><tbody><tr><td><code>ids</code></td><td><code>string</code></td><td>Идентификаторы <a href="',
    this.routePath('datatypes'), // @303:35
    '#Place">мест</a>, разделенных запятыми</td></tr></tbody></table><p>В ответ выдается список идентификаторов <a href="',
    this.routePath('datatypes'), // @307:53
    '#Place">мест</a>, которые были удалены у пользователя:</p><pre js>{\n  data: Array.&lt;uint&gt;\n}</pre><h2>Добавление образование</h2><div class=\'request\'><div class=\'method\'>POST</div><div class=\'path\'>/v201405/me/education</div></div><table class=\'params\'><caption>POST параметры</caption><thead><tr><th>Название</th><th>Тип</th><th>Описание</th></tr></thead><tbody><tr><td><code>fromYear</code></td><td><code>uint=</code></td><td>Год начала обучения</td></tr><tr><td><code>schoolId</code></td><td><code>uint=</code></td><td>Идентификатор <a href="',
    this.routePath('datatypes'), // @337:34
    '#School">учебного заведения</a></td></tr><tr><td><code>schoolName</code></td><td><code>string=</code></td><td>Название <a href="',
    this.routePath('datatypes'), // @342:29
    '#School">учебного заведения</a></td></tr><tr><td><code>specialityId</code></td><td><code>uint=</code></td><td>Идентификатор <a href="',
    this.routePath('datatypes'), // @347:34
    '#Speciality">специальности</a></td></tr><tr><td><code>specialityName</code></td><td><code>string=</code></td><td>Название <a href="',
    this.routePath('datatypes'), // @352:29
    '#Speciality">специальности</a></td></tr><tr><td><code>toYear</code></td><td><code>uint=</code></td><td>Год завершения обучения</td></tr></tbody></table><p>Ответ:</p><pre js>{\n  data: <a href="',
    this.routePath('datatypes'), // @364:18
    '#EducationItem">EducationItem</a>',
    '\n', // @364:83
    '}</pre><p>В случае пустого значения параметров <code>schoolId</code> и <code>schoolName</code> или если учебное заведение с данным идентификатором не была найдено в базе, выдается ответ со статусом 403 и данными:</p><pre js>{\n  error: {\n    code: <a href=\'',
    this.routePath('datatypes'), // @371:20
    '#ErrorCode_WRONG_PARAMS\'>ErrorCode.WRONG_PARAMS</a>,\n    params: [{\n      code: <a href=\'',
    this.routePath('datatypes'), // @373:22
    '#ErrorCode_REQUIRED\'>ErrorCode.REQUIRED</a>,\n      name: \'school\'\n    }]\n  }\n}</pre><h2>Удаление образования</h2><div class=\'request\'><div class=\'method\'>DELETE</div><div class=\'path\'>/v201405/me/education</div></div><table class=\'params\'><caption>GET параметры</caption><thead><tr><th>Название</th><th>Тип</th><th>Описание</th></tr></thead><tbody><tr><td><code>ids</code></td><td><code>string</code></td><td>Идентификаторы <a href="',
    this.routePath('datatypes'), // @398:35
    '#EducationItem">образования</a>, разделенных запятыми</td></tr></tbody></table><p>В ответ выдается список идентификаторов <a href="',
    this.routePath('datatypes'), // @402:53
    '#EducationItem">образования</a>, которые были удалены у пользователя:</p><pre js>{\n  data: Array.&lt;uint&gt;\n}</pre>'
  );
}; // @408:1

module.exports = Page;
