// Content below is autogenerated by ojster template engine
// usually there is no reason to edit it manually
"use strict";
var inherits = require('util').inherits;
var LayoutTemplate = require('../../layout');

var Page = function (opt_data, opt_ctx, opt_writer) {
  LayoutTemplate.call(this, opt_data, opt_ctx, opt_writer);
};
inherits(Page, LayoutTemplate);


Page.prototype.renderBlockContentInternal = function () { // @7:1
  var self = this;
  var d = this.data, vars = this.vars;
  self.writer.write(
    '<h2>Загрузка фотографии</h2><div class=\'request\'><div class=\'method\'>POST</div><div class=\'path\'>/v201405/photos/add</div><div class=\'auth\'>Требуется <a href="',
    this.routePath('auth'), // @12:40
    '#signin">авторизация</a></div></div><table class=\'params\'><caption>POST параметры</caption><thead><tr><th>Название</th><th>Тип</th><th>Описание</th></tr></thead><tbody><tr><td><code>image</code></td><td><code>File</code></td><td>Файл изображения</td></tr></tbody></table><p>Ответ:</p><pre js>{\n  data: {\n    photo: <a href="',
    this.routePath('datatypes'), // @34:21
    '#Photo">Photo</a>',
    '\n  ', // @34:70
    '}\n}</pre><p>В случае неправильного формата файла выводится ошибка со статусом 403:</p><pre js>{\n  error: {\n    code: <a href=\'',
    this.routePath('datatypes'), // @42:20
    '#ErrorCode_WRONG_FILE_FORMAT\'>ErrorCode.WRONG_FILE_FORMAT</a>',
    '\n  ', // @42:113
    '}\n}</pre><p>В случае слишком большого размера файла выводится ошибка со статусом 403:</p><pre js>{\n  error: {\n    code: <a href=\'',
    this.routePath('datatypes'), // @50:20
    '#ErrorCode_TOO_LARGE_FILE\'>ErrorCode.TOO_LARGE_FILE</a>',
    '\n  ', // @50:107
    '}\n}</pre><p>В случае слишком маленького размера изображения выводится ошибка со статусом 403:</p><pre js>{\n  error: {\n    code: <a href=\'',
    this.routePath('datatypes'), // @58:20
    '#ErrorCode_TOO_SMALL_SIZE\'>ErrorCode.TOO_SMALL_SIZE</a>',
    '\n  ', // @58:107
    '}\n}</pre><h2>Удаление фотографии</h2><div class=\'request\'><div class=\'method\'>POST</div><div class=\'path\'>/v201405/photos/&lt;id&gt;/remove</div><div class=\'auth\'>Требуется <a href="',
    this.routePath('auth'), // @67:40
    '#signin">авторизация</a></div></div><table class=\'params\'><caption>Параметры адреса</caption><thead><tr><th>Название</th><th>Тип</th><th>Описание</th></tr></thead><tbody><tr><td><code>id</code></td><td><code>uint</code></td><td>Идентификатор <a href="',
    this.routePath('datatypes'), // @82:34
    '#Photo">фотографии</a></td></tr></tbody></table><p>В ответе выдается идентификатор удаленной фотографии:</p><pre js>{\n  data: {\n    id: uint\n  }\n}</pre><p>Возможные ошибки:</p><ul><li><a href="',
    this.routePath('http'), // @95:16
    '#error404">объект не найден</a></li><li><a href="',
    this.routePath('http'), // @96:16
    '#errorAccessDenied">отказано в доступе</a></li></ul>'
  );
}; // @98:1

module.exports = Page;
