// Content below is autogenerated by ojster template engine
// usually there is no reason to edit it manually
"use strict";
var inherits = require('util').inherits;
var LayoutTemplate = require('../../layout');

var Page = function (opt_data, opt_ctx, opt_writer) {
  LayoutTemplate.call(this, opt_data, opt_ctx, opt_writer);
};
inherits(Page, LayoutTemplate);


Page.prototype.renderBlockContentInternal = function () { // @7:1
  var self = this;
  var d = this.data, vars = this.vars;
  self.writer.write(
    '<h2 id=\'get\'>Список элементов справочника</h2><div class=\'request\'><div class=\'method\'>GET</div><div class=\'path\'>/v201405/reference</div></div><table class=\'params\'><caption>GET параметры</caption><thead><tr><th>Название</th><th>Тип</th><th>Описание</th></tr></thead><tbody><tr><td><code>careerPostIds</code></td><td><code>string=</code></td><td>Идентификаторы <a href="',
    this.routePath('datatypes'), // @26:35
    '#CareerPost">должностей</a>, разделенных запятыми</td></tr><tr><td><code>companyIds</code></td><td><code>string=</code></td><td>Идентификаторы <a href="',
    this.routePath('datatypes'), // @31:35
    '#Company">компаний</a>, разделенных запятыми</td></tr><tr><td><code>languageIds</code></td><td><code>string=</code></td><td>Идентификаторы <a href="',
    this.routePath('datatypes'), // @36:35
    '#Language">языков</a>, разделенных запятыми</td></tr><tr><td><code>placeIds</code></td><td><code>string=</code></td><td>Идентификаторы <a href="',
    this.routePath('datatypes'), // @41:35
    '#Place">мест</a>, разделенных запятыми</td></tr><tr><td><code>schoolIds</code></td><td><code>string=</code></td><td>Идентификаторы <a href="',
    this.routePath('datatypes'), // @46:35
    '#School">учебных заведений</a>, разделенных запятыми</td></tr><tr><td><code>specialityIds</code></td><td><code>string=</code></td><td>Идентификаторы <a href="',
    this.routePath('datatypes'), // @51:35
    '#Speciality">специальностей</a>, разделенных запятыми</td></tr></tbody></table><p>Ответ:</p><pre js>{\n  data: {\n    careerPosts: Array.&lt;<a href="',
    this.routePath('datatypes'), // @59:37
    '#CareerPost">CareerPost</a>&gt;=,\n    companies: Array.&lt;<a href="',
    this.routePath('datatypes'), // @60:35
    '#Company">Company</a>&gt;=,\n    languages: Array.&lt;<a href="',
    this.routePath('datatypes'), // @61:35
    '#Language">Language</a>&gt;=,\n    places: Array.&lt;<a href="',
    this.routePath('datatypes'), // @62:32
    '#Place">Place</a>&gt;=,\n    schools: Array.&lt;<a href="',
    this.routePath('datatypes'), // @63:33
    '#School">School</a>&gt;=,\n    specialities: Array.&lt;<a href="',
    this.routePath('datatypes'), // @64:38
    '#Speciality">Speciality</a>&gt;=\n  }\n}</pre><h2>Поиск должностей</h2><div class=\'request\'><div class=\'method\'>GET</div><div class=\'path\'>/v201405/reference/career-posts/find</div></div><table class=\'params\'><caption>GET параметры</caption><thead><tr><th>Название</th><th>Тип</th><th>Описание</th></tr></thead><tbody><tr><td><code>query</code></td><td><code>string</code></td><td>Строка запроса</td></tr><tr><td><code>limit</code></td><td><code>uint=</code></td><td>Ограничение в количестве должностей. Максимум — 20</td></tr></tbody></table><p>Осуществляет поиск должностей по строке. Поиск осуществляется без учета регистра.</p><p>Ответ:</p><pre js>{\n  data: Array.&lt;<a href="',
    this.routePath('datatypes'), // @100:28
    '#CareerPost">CareerPost</a>&gt;\n}</pre><p>Порядок, в котором отдаются должности:</p><ol><li>Строка запроса и название должности совпадают.</li><li>Название должности начинается со строки запроса.</li><li>Строка запроса присутствует в названиии должности.</li></ol><h2>Поиск компаний</h2><div class=\'request\'><div class=\'method\'>GET</div><div class=\'path\'>/v201405/reference/companies/find</div></div><table class=\'params\'><caption>GET параметры</caption><thead><tr><th>Название</th><th>Тип</th><th>Описание</th></tr></thead><tbody><tr><td><code>query</code></td><td><code>string</code></td><td>Строка запроса</td></tr><tr><td><code>limit</code></td><td><code>uint=</code></td><td>Ограничение в количестве компаний. Максимум — 20</td></tr></tbody></table><p>Осуществляет поиск компаний по строке. Поиск осуществляется без учета регистра.</p><p>Ответ:</p><pre js>{\n  data: Array.&lt;<a href="',
    this.routePath('datatypes'), // @141:28
    '#Company">Company</a>&gt;\n}</pre><p>Порядок, в котором отдаются компании:</p><ol><li>Строка запроса и название компании совпадают.</li><li>Название компании начинается со строки запроса.</li><li>Строка запроса присутствует в названиии компании.</li></ol><h2>Поиск языков</h2><div class=\'request\'><div class=\'method\'>GET</div><div class=\'path\'>/v201405/reference/languages/find</div></div><table class=\'params\'><caption>GET параметры</caption><thead><tr><th>Название</th><th>Тип</th><th>Описание</th></tr></thead><tbody><tr><td><code>query</code></td><td><code>string</code></td><td>Строка запроса</td></tr><tr><td><code>limit</code></td><td><code>uint=</code></td><td>Ограничение в количестве языков. Максимум — 20</td></tr></tbody></table><p>Осуществляет поиск языков по строке. Поиск осуществляется без учета регистра.</p><p>Ответ:</p><pre js>{\n  data: Array.&lt;<a href="',
    this.routePath('datatypes'), // @182:28
    '#Language">Language</a>&gt;\n}</pre><p>Порядок, в котором отдаются языки:</p><ol><li>Строка запроса и название языка совпадают.</li><li>Название языка начинается со строки запроса.</li><li>Строка запроса присутствует в названиии языка.</li></ol><h2>Поиск мест</h2><div class=\'request\'><div class=\'method\'>GET</div><div class=\'path\'>/v201405/reference/places/find</div></div><table class=\'params\'><caption>GET параметры</caption><thead><tr><th>Название</th><th>Тип</th><th>Описание</th></tr></thead><tbody><tr><td><code>query</code></td><td><code>string</code></td><td>Строка запроса</td></tr><tr><td><code>limit</code></td><td><code>uint=</code></td><td>Ограничение в количестве мест. Максимум — 20</td></tr></tbody></table><p>Осуществляет поиск мест по строке. Поиск осуществляется без учета регистра.</p><p>Ответ:</p><pre js>{\n  data: Array.&lt;<a href="',
    this.routePath('datatypes'), // @223:28
    '#Place">Place</a>&gt;\n}</pre><p>Порядок, в котором отдаются места:</p><ol><li>Строка запроса и название места совпадают.</li><li>Название места начинается со строки запроса.</li><li>Строка запроса присутствует в названиии места.</li></ol><h2>Поиск учебных заведений</h2><div class=\'request\'><div class=\'method\'>GET</div><div class=\'path\'>/v201405/reference/schools/find</div></div><table class=\'params\'><caption>GET параметры</caption><thead><tr><th>Название</th><th>Тип</th><th>Описание</th></tr></thead><tbody><tr><td><code>query</code></td><td><code>string</code></td><td>Строка запроса</td></tr><tr><td><code>limit</code></td><td><code>uint=</code></td><td>Ограничение в количестве учебных заведений. Максимум — 20</td></tr></tbody></table><p>Осуществляет поиск учебных заведений по строке. Поиск осуществляется без учета регистра.</p><p>Ответ:</p><pre js>{\n  data: Array.&lt;<a href="',
    this.routePath('datatypes'), // @264:28
    '#School">School</a>&gt;\n}</pre><p>Порядок, в котором отдаются учебные заведения:</p><ol><li>Строка запроса и название учебного заведения совпадают.</li><li>Название учебного заведения начинается со строки запроса.</li><li>Строка запроса присутствует в названиии учебного заведения.</li></ol><h2>Поиск специальностей</h2><div class=\'request\'><div class=\'method\'>GET</div><div class=\'path\'>/v201405/reference/specialities/find</div></div><table class=\'params\'><caption>GET параметры</caption><thead><tr><th>Название</th><th>Тип</th><th>Описание</th></tr></thead><tbody><tr><td><code>query</code></td><td><code>string</code></td><td>Строка запроса</td></tr><tr><td><code>limit</code></td><td><code>uint=</code></td><td>Ограничение в количестве специальностей. Максимум — 20</td></tr></tbody></table><p>Осуществляет поиск специальностей по строке. Поиск осуществляется без учета регистра.</p><p>Ответ:</p><pre js>{\n  data: Array.&lt;<a href="',
    this.routePath('datatypes'), // @305:28
    '#Speciality">Speciality</a>&gt;\n}</pre><p>Порядок, в котором отдаются специальности:</p><ol><li>Строка запроса и название специальности совпадают.</li><li>Название специальности начинается со строки запроса.</li><li>Строка запроса присутствует в названиии специальности.</li></ol>'
  );
}; // @314:1

module.exports = Page;
