// Content below is autogenerated by ojster template engine
// usually there is no reason to edit it manually
"use strict";
var inherits = require('util').inherits;
var LayoutTemplate = require('../../layout');

var Page = function (opt_data, opt_ctx, opt_writer) {
  LayoutTemplate.call(this, opt_data, opt_ctx, opt_writer);
};
inherits(Page, LayoutTemplate);


Page.prototype.renderBlockContentInternal = function () { // @7:1
  var self = this;
  var d = this.data, vars = this.vars;
  self.writer.write(
    '<h2 id="get">Получение настроек</h2><div class=\'request\'><div class=\'method\'>GET</div><div class=\'path\'>/v201405/settings</div></div><p>Ответ:</p><pre js>{\n  data: {\n    settings: <a href="',
    this.routePath('datatypes'), // @17:24
    '#Settings">Settings</a>',
    '\n  ', // @17:79
    '}\n}</pre>'
  );
}; // @21:1

module.exports = Page;
