// Content below is autogenerated by ojster template engine
// usually there is no reason to edit it manually
"use strict";
var inherits = require('util').inherits;
var Template = require('../core/template');

var Layout = function (opt_data, opt_ctx, opt_writer) {
  Template.call(this, opt_data, opt_ctx, opt_writer);
};
inherits(Layout, Template);


Layout.prototype.renderBlockMain = function () { // @7:1
  var self = this;
  var d = this.data, vars = this.vars;
  self.writer.write(
    '<!DOCTYPE html><html><head><meta http-equiv=\'Content-Type\' content=\'text/html; charset=utf-8\'><title>',
    d.title, // @12:12
    '</title><link media=\'all\' rel=\'stylesheet\' type=\'text/css\' href=\'',
    this.relativePath('/s/css/main.css'), // @13:62
    '\'></head><body>'
  ); // @16:5
  self.renderBlockPage(); // @16:5
  self.writer.write(
    '</body></html>'
  );
}; // @19:1


Layout.prototype.renderBlockPage = function () { // @22:1
  var self = this;
  var d = this.data, vars = this.vars;
  self.renderBlockContent(); // @23:1
  self.renderBlockSidebar(); // @24:1
}; // @25:1


Layout.prototype.renderBlockContent = function () { // @28:1
  var self = this;
  var d = this.data, vars = this.vars;
  self.writer.write(
    '<div class="content"><h1>',
    d.header, // @30:7
    '</h1>'
  ); // @31:3
  self.renderBlockContentInternal(); // @31:3
  self.writer.write(
    '</div>'
  );
}; // @33:1


Layout.prototype.renderBlockSidebar = function () { // @36:1
  var self = this;
  var d = this.data, vars = this.vars;
  self.writer.write(
    '<div class=\'sidebar\'>'
  ); // @38:3
  self.renderBlockNavigationItems(d.navigation); // @38:3
  self.writer.write(
    '<div class=\'toggle\'></div></div>'
  );
}; // @41:1


Layout.prototype.renderBlockNavigationItems = function (items) { // @44:1
  var self = this;
  var d = this.data, vars = this.vars;
  self.writer.write(
    '<div class=\'navigation\'>'
  ); // @46:3

  items.forEach(function(item) {


      var url = item.getUrl();
      var childs = item.getChilds();

  self.writer.write(
    '<div class=\'item\'>'
  ); // @52:7

  if (url && d.url != url) {

  self.writer.write(
    '<a href="',
    this.relativePath(url), // @53:18
    '">'
  ); // @54:7

  }

  self.writer.write(
    item.getNavigationTitle() // @56:7
  ); // @58:7

  if (url && d.url != url) {

  self.writer.write(
    '</a>'
  ); // @60:7

  }


  if (childs.length) {

  self.renderBlockNavigationItems(childs); // @63:9

  }

  self.writer.write(
    '</div>'
  ); // @66:3

  }, this);

  self.writer.write(
    '</div>'
  );
}; // @68:1

module.exports = Layout;
